package com.NewTask.entity.dao;
// Generated 20 Apr 2023, 21:58:50 by Hibernate Tools 6.1.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="post"
    ,catalog="tasks"
)
public class Post  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String tittle;
     private String body;
     private String comments;
     private String likes;
     private Set<Review> reviews = new HashSet<Review>(0);

    public Post() {
    }

	
    public Post(User user, String tittle) {
        this.user = user;
        this.tittle = tittle;
    }
    public Post(User user, String tittle, String body, String comments, String likes, Set<Review> reviews) {
       this.user = user;
       this.tittle = tittle;
       this.body = body;
       this.comments = comments;
       this.likes = likes;
       this.reviews = reviews;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    @JsonIgnore
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="tittle", nullable=false, length=45)
    public String getTittle() {
        return this.tittle;
    }
    
    public void setTittle(String tittle) {
        this.tittle = tittle;
    }

    
    @Column(name="body", length=45)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="comments", length=45)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="likes", length=45)
    public String getLikes() {
        return this.likes;
    }
    
    public void setLikes(String likes) {
        this.likes = likes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="post")
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }




}


