package com.NewTask.entity.dao;
// Generated 20 Apr 2023, 21:58:50 by Hibernate Tools 6.1.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="review"
    ,catalog="tasks"
)
public class Review  implements java.io.Serializable {


     private int reviewId;
     private Post post;
     private String rate;

    public Review() {
    }

	
    public Review(int reviewId, Post post) {
        this.reviewId = reviewId;
        this.post = post;
    }
    public Review(int reviewId, Post post, String rate) {
       this.reviewId = reviewId;
       this.post = post;
       this.rate = rate;
    }
   
     @Id 

    
    @Column(name="review_id", unique=true, nullable=false)
    public int getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(int reviewId) {
        this.reviewId = reviewId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="post_id", nullable=false)
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }

    
    @Column(name="rate", length=45)
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }




}


