package com.NewTask.entity.dao;
// Generated 20 Apr 2023, 21:58:50 by Hibernate Tools 6.1.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="tasks"
    , uniqueConstraints = @UniqueConstraint(columnNames="User_email") 
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userEmail;
     private String userName;
     private Set<Post> posts = new HashSet<Post>(0);

    public User() {
    }

    public User(String userEmail, String userName, Set<Post> posts) {
       this.userEmail = userEmail;
       this.userName = userName;
       this.posts = posts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="User_email", unique=true, length=45)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="user_name", length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
 
@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }




}


